title: Emmanouela Rantsiou # your name (or website title) here
logo: "/images/cassata-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  mostly a physicist; 
  <br> mainly interested in DL & <br> animal congnition and behaviour
  <hr> 
  <br>
  some other stuff about me
  <hr> 
  <br>
  <a href="https://www.linkedin.com/in/emmanouela-rantsiou/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-221464782-1 # your Google Analytics tracking ID here
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:identitydecentralized@gmail.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://decentralized-id.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/decentralizeid"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/decentralized-id"
