title: Emmanouela Rantsiou # your name (or website title) here
logo: "/images/IMG_4270.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/emmanouela-rantsiou/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-221464782-1 # your Google Analytics tracking ID here
